name: Tag Version
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
    outputs:
      version_tag:
        description: "Generated version tag"
        value: ${{ jobs.tag.outputs.version_tag }}

jobs:
  tag:
    # ðŸ³ Run job inside this container image
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim

    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.generate-tag.outputs.version_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --------------------------------
      # Write all variables to file
      - name: Write environment variables to file
        run: |
          mkdir -p artifacts
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> artifacts/env_vars.txt
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> artifacts/env_vars.txt
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> artifacts/env_vars.txt
          echo "VERSION_TAG=dev-${{ github.run_number }}" >> artifacts/env_vars.txt
          echo "âœ… Saved all variables to artifacts/env_vars.txt"

      # --------------------------------
      # Upload as artifact
      - name: Upload environment file
        uses: actions/upload-artifact@v4
        with:
          name: aws-env-vars
          path: artifacts/env_vars.txt
          retention-days: 1
